name: easyrise
description: "EasyRise - a soothing alarm clock that makes you solve a gentle puzzle to wake up, with satisfying streaks."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  alarm: ^5.0.0
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
